back_squat = Lift.create(name: 'Back Squat')
front_squat = Lift.create(name: 'Front Squat')
shoulder_press = Lift.create(name: 'Shoulder Press')
push_press = Lift.create(name: 'Push Press')
bench_press = Lift.create(name: 'Bench Press')
deadlift = Lift.create(name: 'Deadlift')
pull_up = Lift.create(name: 'Pull Up')
dip = Lift.create(name: 'Dip')

back_squat.results.create(date: Date.today, rep_scheme: 3, load: 285, notes: "tried 315, but only got 2")